// Synthetic scam-report seed for the scam-intelligence network.
// SYNTHETIC DEMO DATA ONLY — fabricated identifiers (R-####), no real people or
// customers. Used to demonstrate semantic + entity matching of new cases.

import { NetworkReport } from './types';

// --- The "Nimbus Talent" ring -------------------------------------------------
// Six reports impersonating DIFFERENT brands while reusing the same
// infrastructure: two domains, one USDT wallet, one Zelle handle, one phone
// number, two recruiter emails. The entity-graph builder promotes these to
// `corroborated` automatically because they share hard identifiers; two are
// `authoritative` (trusted). This is what the demo's "ring reveal" computes over.
const NIMBUS_RING: NetworkReport[] = [
  {
    reportId: 'R-2001',
    companyName: 'Google',
    aliases: ['Daniel Okafor', 'Google Remote Hiring'],
    scamType: 'Brand impersonation / crypto deposit',
    description:
      'Recruiter "Daniel Okafor" offered a remote Google QA role, interviewed entirely over chat, and required a refundable USDT equipment deposit to wallet TQrKp4mNbu77 before onboarding.',
    domains: ['nimbus-talent-hr.com'],
    emails: ['d.okafor@nimbus-talent-hr.com'],
    phones: ['+1 (332) 555-0144'],
    paymentHandles: ['USDT wallet: TQrKp4mNbu77'],
    location: 'Remote (US)',
    reportedAt: '2026-04-14',
    sourceType: 'seed',
  },
  {
    reportId: 'R-2002',
    companyName: 'Stripe',
    aliases: ['Nimbus Talent Partners', 'Stripe Talent Ops'],
    scamType: 'Brand impersonation / onboarding fee',
    description:
      'A "Stripe partner agency" called Nimbus Talent ran a WhatsApp interview and asked for a $180 background-check fee via Zelle (nimbus-onboard) before issuing the offer letter.',
    domains: ['nimbustalent-careers.net'],
    emails: ['hr@nimbustalent-careers.net'],
    phones: ['+1 (332) 555-0144'],
    paymentHandles: ['Zelle: nimbus-onboard'],
    location: 'Remote (US)',
    reportedAt: '2026-04-29',
    sourceType: 'seed',
  },
  {
    reportId: 'R-2003',
    companyName: 'Shopify',
    aliases: ['Daniel Okafor', 'Shopify Hiring Desk'],
    scamType: 'Brand impersonation / equipment fee',
    description:
      'Shopify "customer success" role from recruiter Daniel Okafor required buying a laptop from a company vendor; payment requested in USDT to wallet TQrKp4mNbu77.',
    domains: ['nimbus-talent-hr.com', 'nimbustalent-careers.net'],
    emails: ['d.okafor@nimbus-talent-hr.com'],
    phones: [],
    paymentHandles: ['USDT wallet: TQrKp4mNbu77'],
    location: 'Remote (CA)',
    reportedAt: '2026-05-09',
    sourceType: 'authoritative',
  },
  {
    reportId: 'R-2004',
    companyName: 'Deloitte',
    aliases: ['Nimbus Talent HR', 'Deloitte Flexible Workforce'],
    scamType: 'Brand impersonation / advance fee',
    description:
      'Deloitte "flexible workforce" data-analyst offer demanded a software licensing fee through Zelle (nimbus-onboard); the recruiter used a WhatsApp number with a +1 332 area code.',
    domains: ['nimbustalent-careers.net'],
    emails: ['hr@nimbustalent-careers.net'],
    phones: ['+1 (332) 555-0144'],
    paymentHandles: ['Zelle: nimbus-onboard'],
    location: 'Remote (US)',
    reportedAt: '2026-05-18',
    sourceType: 'seed',
  },
  {
    reportId: 'R-2005',
    companyName: 'Sterling Staffing Co',
    aliases: ['Nimbus Talent', 'Sterling Remote Jobs'],
    scamType: 'Fake staffing agency / crypto deposit',
    description:
      'A staffing agency front ("Sterling Staffing") recycled the same pitch: guaranteed remote roles after a commitment deposit in USDT to wallet TQrKp4mNbu77.',
    domains: ['nimbus-talent-hr.com'],
    emails: ['onboarding@nimbus-talent-hr.com'],
    phones: [],
    paymentHandles: ['USDT wallet: TQrKp4mNbu77'],
    location: 'Remote (global)',
    reportedAt: '2026-05-27',
    sourceType: 'authoritative',
  },
  {
    reportId: 'R-2006',
    companyName: 'Meta',
    aliases: ['Daniel Okafor', 'Meta Contract Talent'],
    scamType: 'Brand impersonation / messaging app',
    description:
      'Meta contractor role offered over Telegram by Daniel Okafor; candidates were told to "verify employment eligibility" by sending a deposit via Zelle (nimbus-onboard).',
    domains: ['nimbustalent-careers.net', 'nimbus-talent-hr.com'],
    emails: ['hr@nimbustalent-careers.net', 'd.okafor@nimbus-talent-hr.com'],
    phones: ['+1 (332) 555-0144'],
    paymentHandles: ['Zelle: nimbus-onboard'],
    location: 'Remote (US)',
    reportedAt: '2026-06-03',
    sourceType: 'seed',
  },
];

export const SEED_REPORTS: NetworkReport[] = [
  ...NIMBUS_RING,
  {
    reportId: 'R-1001',
    companyName: 'Google',
    aliases: ['Google Hiring Team', 'Google Careers HR'],
    scamType: 'Brand impersonation / advance fee',
    description:
      'Recruiter claiming to be from Google fast-tracked a Software Engineer role and asked for a $250 onboarding fee paid in gift cards before a contract was sent.',
    domains: ['google-hiring-team.com', 'google-careers-portal.net'],
    emails: ['careers@google-hiring-team.com'],
    paymentHandles: ['gift card: Apple', 'gift card: Steam'],
    location: 'Remote (US)',
    reportedAt: '2026-05-21',
  },
  {
    reportId: 'R-1002',
    companyName: 'Remote Data Solutions',
    aliases: ['RDS Staffing'],
    scamType: 'Equipment fee / data entry',
    description:
      'Unsolicited remote data-entry offer at $45/hour requiring a $250 refundable equipment fee via gift card, with urgent pressure to start the same day.',
    domains: ['remotedatasolutions-jobs.com'],
    emails: ['hr@remotedatasolutions-jobs.com'],
    paymentHandles: ['gift card: Google Play'],
    location: 'Remote (US)',
    reportedAt: '2026-05-30',
  },
  {
    reportId: 'R-1003',
    companyName: 'Amazon',
    aliases: ['Amazon Talent Acquisition', 'Amazon Work-From-Home'],
    scamType: 'Brand impersonation / check overpayment',
    description:
      'Fake Amazon work-from-home recruiter mailed a check to buy a home office setup, then asked the victim to wire back the difference before the check bounced.',
    domains: ['amazon-wfh-careers.com'],
    emails: ['recruiting@amazon-wfh-careers.com'],
    paymentHandles: ['wire transfer', 'Zelle: amzn-setup'],
    location: 'Phoenix, AZ',
    reportedAt: '2026-04-18',
  },
  {
    reportId: 'R-1004',
    companyName: 'CryptoWealth Careers',
    aliases: ['CW Trading Desk'],
    scamType: 'Crypto investment job',
    description:
      'Telegram recruiter offered a crypto trading-assistant job that required depositing USDT into a company wallet to "activate" the account and unlock commissions.',
    domains: ['cryptowealth-careers.io'],
    emails: ['hr@cryptowealth-careers.io'],
    paymentHandles: ['USDT wallet: TXh9...k2', 'crypto: BTC'],
    location: 'Remote (global)',
    reportedAt: '2026-05-11',
  },
  {
    reportId: 'R-1005',
    companyName: 'Meta',
    aliases: ['Meta Recruiting', 'Facebook HR'],
    scamType: 'Brand impersonation / messaging app',
    description:
      'Recruiter posing as Meta conducted the entire "interview" over WhatsApp and requested a background-check fee via Cash App before an offer letter.',
    domains: ['meta-careers-hr.com'],
    emails: ['talent@meta-careers-hr.com'],
    paymentHandles: ['Cash App: $metahr'],
    location: 'Remote (US)',
    reportedAt: '2026-06-02',
  },
  {
    reportId: 'R-1006',
    companyName: 'Global Mystery Shoppers',
    aliases: ['GMS Evaluations'],
    scamType: 'Mystery shopper / money mule',
    description:
      'Mystery-shopper "job" sent a check to evaluate a money-transfer service; the task was to wire most of the funds and keep a commission.',
    domains: ['globalmysteryshoppers.net'],
    emails: ['jobs@globalmysteryshoppers.net'],
    paymentHandles: ['MoneyGram', 'Western Union'],
    location: 'Dallas, TX',
    reportedAt: '2026-03-27',
  },
  {
    reportId: 'R-1007',
    companyName: 'Swift Parcel Logistics',
    aliases: ['Swift Reshipping'],
    scamType: 'Reshipping / package mule',
    description:
      'Work-from-home "logistics coordinator" role asked the victim to receive packages and reship them abroad, unknowingly laundering stolen goods.',
    domains: ['swiftparcel-logistics.com'],
    emails: ['hr@swiftparcel-logistics.com'],
    paymentHandles: ['promised PayPal payout'],
    location: 'Newark, NJ',
    reportedAt: '2026-04-09',
  },
  {
    reportId: 'R-1008',
    companyName: 'Microsoft',
    aliases: ['Microsoft Staffing', 'MSFT Careers'],
    scamType: 'Brand impersonation / look-alike domain',
    description:
      'Fake Microsoft recruiter used a look-alike domain and asked candidates to purchase a "training kit" via gift card before onboarding.',
    domains: ['microsoft-staffing-team.com'],
    emails: ['careers@microsoft-staffing-team.com'],
    paymentHandles: ['gift card: Microsoft', 'gift card: Amazon'],
    location: 'Remote (US)',
    reportedAt: '2026-05-25',
  },
  {
    reportId: 'R-1009',
    companyName: 'Horizon Virtual Assistants',
    aliases: ['Horizon VA'],
    scamType: 'Advance fee / equipment',
    description:
      'Virtual assistant position required buying a specific laptop from a "company vendor" by sending an e-transfer up front, after which the recruiter vanished.',
    domains: ['horizon-va-careers.com'],
    emails: ['apply@horizon-va-careers.com'],
    paymentHandles: ['Interac e-transfer', 'Zelle'],
    location: 'Toronto, ON',
    reportedAt: '2026-05-04',
  },
  {
    reportId: 'R-1010',
    companyName: 'Bright Future Recruiting',
    aliases: ['BFR Talent'],
    scamType: 'Visa / relocation fee',
    description:
      'Overseas job offer promised visa sponsorship but required an up-front processing and relocation fee wired to a personal account.',
    domains: ['brightfuture-recruiting.org'],
    emails: ['visa@brightfuture-recruiting.org'],
    paymentHandles: ['wire transfer'],
    location: 'Remote (international)',
    reportedAt: '2026-02-14',
  },
  {
    reportId: 'R-1011',
    companyName: 'Apple',
    aliases: ['Apple At-Home Advisor', 'Apple HR'],
    scamType: 'Brand impersonation / gift card',
    description:
      'Recruiter impersonating Apple offered an At-Home Advisor role and required gift cards to "reserve" equipment, citing limited slots and urgency.',
    domains: ['apple-athome-careers.com'],
    emails: ['hr@apple-athome-careers.com'],
    paymentHandles: ['gift card: Apple'],
    location: 'Remote (US)',
    reportedAt: '2026-06-01',
  },
  {
    reportId: 'R-1012',
    companyName: 'NextGen Staffing Group',
    aliases: ['NextGen HR'],
    scamType: 'Check overpayment',
    description:
      'Administrative assistant role sent a fraudulent check for supplies and asked the victim to forward part of it to a "vendor" via Zelle.',
    domains: ['nextgen-staffinggroup.com'],
    emails: ['payroll@nextgen-staffinggroup.com'],
    paymentHandles: ['Zelle: nextgen-vendor'],
    location: 'Atlanta, GA',
    reportedAt: '2026-03-12',
  },
  {
    reportId: 'R-1013',
    companyName: 'Oceanic Shipping Careers',
    aliases: ['Oceanic Crew'],
    scamType: 'Visa / agency fee',
    description:
      'Cruise-ship hospitality jobs required payment of an agency and medical-exam fee through an untraceable voucher before any contract.',
    domains: ['oceanic-shipping-careers.com'],
    emails: ['crew@oceanic-shipping-careers.com'],
    paymentHandles: ['voucher: Neosurf'],
    location: 'Manila, PH',
    reportedAt: '2026-04-30',
  },
  {
    reportId: 'R-1014',
    companyName: 'PrimeChat Support',
    aliases: ['PrimeChat HR'],
    scamType: 'Chat-agent / training fee',
    description:
      'Live-chat support role advertised on social media required a refundable training fee paid in crypto, with guaranteed high pay and immediate start.',
    domains: ['primechat-support-jobs.com'],
    emails: ['hiring@primechat-support-jobs.com'],
    paymentHandles: ['crypto: ETH', 'gift card: Amazon'],
    location: 'Remote (US)',
    reportedAt: '2026-05-19',
  },
  {
    reportId: 'R-1015',
    companyName: 'Sterling Financial Group',
    aliases: ['Sterling Payroll'],
    scamType: 'Payroll / bank credential phishing',
    description:
      'Offer letter asked new hires to set up direct deposit by submitting full online-banking login credentials through a third-party form.',
    domains: ['sterling-financialgroup.com'],
    emails: ['payroll@sterling-financialgroup.com'],
    paymentHandles: ['bank credentials requested'],
    location: 'Remote (US)',
    reportedAt: '2026-05-08',
  },
  {
    reportId: 'R-1016',
    companyName: 'Google',
    aliases: ['Google Careers Team'],
    scamType: 'Brand impersonation / equipment fee',
    description:
      'Second Google-impersonation report: recruiter on a look-alike domain promised a remote role and asked for a refundable equipment deposit via gift card.',
    domains: ['google-careers-portal.net'],
    emails: ['hr@google-careers-portal.net'],
    paymentHandles: ['gift card: Apple'],
    location: 'Remote (US)',
    reportedAt: '2026-06-04',
  },
  {
    reportId: 'R-1017',
    companyName: 'Velocity Marketing Co',
    aliases: ['Velocity MLM'],
    scamType: 'MLM / recruitment pyramid',
    description:
      'A "marketing manager" role was actually an MLM requiring a starter-kit purchase and recruiting friends to earn back the entry fee.',
    domains: ['velocity-marketing-co.com'],
    emails: ['team@velocity-marketing-co.com'],
    paymentHandles: ['credit card: starter kit'],
    location: 'Remote (US)',
    reportedAt: '2026-03-03',
  },
  {
    reportId: 'R-1018',
    companyName: 'TechBridge Solutions',
    aliases: ['TechBridge HR'],
    scamType: 'Fake interview / data harvesting',
    description:
      'A polished but fake interview process collected passport scans, SSN and a photo of a bank card "for verification" before any job existed.',
    domains: ['techbridge-solutions-hr.com'],
    emails: ['recruitment@techbridge-solutions-hr.com'],
    paymentHandles: ['identity documents requested'],
    location: 'Remote (US)',
    reportedAt: '2026-05-16',
  },
  {
    reportId: 'R-1019',
    companyName: 'BlueWave Staffing',
    aliases: ['BlueWave'],
    scamType: 'Equipment fee / gift card',
    description:
      'Customer-service role required buying a headset and software license from a "preferred supplier" using gift cards before the first shift.',
    domains: ['bluewave-staffing.net'],
    emails: ['jobs@bluewave-staffing.net'],
    paymentHandles: ['gift card: Walmart'],
    location: 'Remote (US)',
    reportedAt: '2026-04-22',
  },
  {
    reportId: 'R-1020',
    companyName: 'Pinnacle Recruiters',
    aliases: ['Pinnacle Talent'],
    scamType: 'Advance fee / crypto',
    description:
      'Remote analyst job required staking a refundable deposit in crypto to a company wallet to demonstrate "commitment" before training.',
    domains: ['pinnacle-recruiters.io'],
    emails: ['hr@pinnacle-recruiters.io'],
    paymentHandles: ['USDT wallet: TJp2...9x'],
    location: 'Remote (global)',
    reportedAt: '2026-05-27',
  },
  {
    reportId: 'R-1021',
    companyName: 'Summit Health Partners',
    aliases: ['Summit HR'],
    scamType: 'Check overpayment / supplies',
    description:
      'Medical-billing work-from-home job mailed a check to buy software, then asked the victim to send the overpayment back via Cash App.',
    domains: ['summit-health-partners.com'],
    emails: ['hr@summit-health-partners.com'],
    paymentHandles: ['Cash App: $summithr'],
    location: 'Houston, TX',
    reportedAt: '2026-03-19',
  },
  {
    reportId: 'R-1022',
    companyName: 'Nimbus Cloud Careers',
    aliases: ['Nimbus HR'],
    scamType: 'Look-alike domain / training fee',
    description:
      'Cloud-support role used a domain mimicking a real provider and charged a certification voucher fee up front, redeemable only through them.',
    domains: ['nimbus-cloud-careers.com'],
    emails: ['careers@nimbus-cloud-careers.com'],
    paymentHandles: ['voucher: certification'],
    location: 'Remote (US)',
    reportedAt: '2026-05-13',
  },
  {
    reportId: 'R-1023',
    companyName: 'Atlas Logistics Hiring',
    aliases: ['Atlas Careers'],
    scamType: 'Reshipping / money mule',
    description:
      'Package-handling role asked the victim to receive and reship parcels and to process "customer refunds" through their personal bank account.',
    domains: ['atlas-logistics-hiring.com'],
    emails: ['hr@atlas-logistics-hiring.com'],
    paymentHandles: ['personal bank account used as mule'],
    location: 'Miami, FL',
    reportedAt: '2026-04-02',
  },
  {
    reportId: 'R-1024',
    companyName: 'EduFuture Tutors',
    aliases: ['EduFuture HR'],
    scamType: 'Advance fee / gift card',
    description:
      'Online-tutoring platform required a background-check and platform-access fee paid in gift cards, promising reimbursement on the first paycheck.',
    domains: ['edufuture-tutors.com'],
    emails: ['tutors@edufuture-tutors.com'],
    paymentHandles: ['gift card: Amazon'],
    location: 'Remote (US)',
    reportedAt: '2026-05-31',
  },
  {
    reportId: 'R-1025',
    companyName: 'Orion Tech Recruiting',
    aliases: ['Orion HR'],
    scamType: 'Crypto deposit / fake desk',
    description:
      'Junior developer role required a wallet deposit to access a "company trading desk" task, with returns shown in a dashboard that could not be withdrawn.',
    domains: ['orion-tech-recruiting.io'],
    emails: ['talent@orion-tech-recruiting.io'],
    paymentHandles: ['USDT wallet: TZk7...44'],
    location: 'Remote (global)',
    reportedAt: '2026-06-05',
  },
  {
    reportId: 'R-1026',
    companyName: 'Coastal Admin Services',
    aliases: ['Coastal HR'],
    scamType: 'Bank credential phishing',
    description:
      'Executive-assistant offer pushed urgent direct-deposit setup through a fake portal harvesting online-banking usernames and one-time passcodes.',
    domains: ['coastal-admin-services.com'],
    emails: ['payroll@coastal-admin-services.com'],
    paymentHandles: ['bank OTP phishing'],
    location: 'Remote (US)',
    reportedAt: '2026-04-26',
  },
];
